name: Deploy dbt docs (Data Catalog) to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --all-groups
          dbt deps

      - name: Prepare connection profile
        run: |
          mkdir -p ~/.dbt
          cp profiles.example.yml ~/.dbt/profiles.yml

      - name: Run linter
        run: |
          source .venv/bin/activate
          sqlfluff lint
        env:
          DBT_ENV_SECRET_PASSWORD: ${{ secrets.DBT_ENV_SECRET_PASSWORD }}

      - name: Generate docs
        run: |
          source .venv/bin/activate
          dbt docs generate
        env:
          DBT_ENV_SECRET_PASSWORD: ${{ secrets.DBT_ENV_SECRET_PASSWORD }}

      - name: Prepare site files
        run: |
          mkdir -p site
          cp target/index.html site/
          cp target/manifest.json site/
          cp target/catalog.json site/

      - name: Commit site for GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site